language: node_js

addons:
  code_climate:
    repo_token: 587f4b0f4745b131c5d936626d49b9c3781faea6a1d56c7c8eaced68220de503

node_js:
  - '4'
  - '5'
  - '6'

before_script:
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < test/coverage/**/lcov.info
