language: node_js

node_js:
  - '0.10'

before_script:
  #- npm install -g codeclimate-test-reporter

after_script:
  #TODO: enable publishing code coverage reports
  #- codeclimate < test/coverage/**/lcov.info

env:
  #- CODECLIMATE_REPO_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
